### ISSUE TITLE
test not passed on Mac 

### ISSUE THREAD

**Issue by CanoeFZH** [meta-toolkit/meta#92] opened 2015-06-10 00:58 UTC
``` 
4/15 Test  #4: inverted-index ...................***Failed    1.42 sec
        inverted-index-build-file-corpus:       [ FAIL ] [idx.unique_terms() == 3944ul] => [3938 == 3944] (inverted_index_test.cpp:69)
        inverted-index-read-file-corpus:        [ FAIL ] [idx.unique_terms() == 3944ul] => [3938 == 3944] (inverted_index_test.cpp:69)
        inverted-index-build-line-corpus:       [ FAIL ] [idx.unique_terms() == 3944ul] => [3938 == 3944] (inverted_index_test.cpp:69)
        inverted-index-read-line-corpus:        [ FAIL ] [idx.unique_terms() == 3944ul] => [3938 == 3944] (inverted_index_test.cpp:69)
        inverted-index-build-gz-corpus:         [ FAIL ] [idx.unique_terms() == 3944ul] => [3938 == 3944] (inverted_index_test.cpp:69)
        inverted-index-read-gz-corpus:          [ FAIL ] [idx.unique_terms() == 3944ul] => [3938 == 3944] (inverted_index_test.cpp:69)

      Start  5: forward-index
 5/15 Test  #5: forward-index ....................***Failed    1.16 sec
        forward-index-build-file-corpus:        [ FAIL ] [idx.unique_terms() == 3944ul] => [3938 == 3944] (forward_index_test.cpp:49)
        forward-index-read-file-corpus:         [ FAIL ] [idx.unique_terms() == 3944ul] => [3938 == 3944] (forward_index_test.cpp:49)
        forward-index-build-line-corpus:        [ FAIL ] [idx.unique_terms() == 3944ul] => [3938 == 3944] (forward_index_test.cpp:49)
        forward-index-read-line-corpus:         [ FAIL ] [idx.unique_terms() == 3944ul] => [3938 == 3944] (forward_index_test.cpp:49)
```

My mac version: 
```
14.3.0 Darwin Kernel Version 14.3.0, root:xnu-2782.20.48~5/RELEASE_X86_64 x86_64
``` 

clang version:
```
Apple LLVM version 6.1.0 (clang-602.0.53) (based on LLVM 3.6.0svn)
Target: x86_64-apple-darwin14.3.0
Thread model: posix
```

**Comment by smassung** [comment] 2015-06-10 01:01
Can you tell us which version of ICU you are using?

**Comment by CanoeFZH** [comment] 2015-06-10 01:02
```
Found ICU: /usr/local/opt/icu4c/lib/libicudata.dylib;/usr/local/opt/icu4c/lib/libicui18n.dylib;/usr/local/opt/icu4c/lib/libicuuc.dylib (found version "55.1.0") 
```
thx for your quick reply.

**Comment by smassung** [comment] 2015-06-10 01:08
Hmm, ok thanks. This looked like a similar issue to one we saw before (different version of ICU splitting words differently). Since you have the latest version of ICU, I'm guessing that's not the case.

We will have to look further into it. I'm guessing it's an issue related to the tokenization somehow.

**Comment by skystrife** [comment] 2015-06-10 01:10
Is this on the master or develop branch?

**Comment by CanoeFZH** [comment] 2015-06-10 01:10
master

**Comment by skystrife** [comment] 2015-06-10 04:41
Could you run 

```
./index config.toml
```

with the following in the config for the corpus (instead of the 20newgroups default):

```toml
corpus-type = "line-corpus"
dataset = "ceeaus"
encoding = "shift_jis"
forward-index = "ceeaus-fwd"
inverted-index = "ceeaus-inv"
```

Attach the final output of that command (the corpus statistics).

And then attach the output of running:

```
./print-vocab ceeaus-inv/termids.mapping
```

(This should let us see what terms are different/missing.)

I tried this on my Mac and couldn't reproduce, but I don't have the exact same versions as you. I'm downloading the Yosemite upgrade ATM and should be able to get the same versions you've got tomorrow, hopefully, to see if I can reproduce.

**Comment by CanoeFZH** [comment] 2015-06-10 05:48
I will run this about 8 hours later. I was using it on my own may laptop and I am at work office now.

**Comment by CanoeFZH** [comment] 2015-06-10 11:24
I am not sure how to change the config for the corpus. 
But: 
```
➜  build git:(master) ./index config.toml 
1433935270: [info]     Creating index: 20news-inv (/Users/canoe/Project/meta/src/index/inverted_index.cpp:118)
libc++abi.dylib: terminating with uncaught exception of type meta::io::mmap_file::mmap_file_exception: error obtaining file descriptor for ../data//20newsgroups/20newsgroups.dat
[1]    9654 abort      ./index config.toml
```

**Comment by tng-konrad** [comment] 2015-06-10 11:25
@CanoeFZH: yup, exact same problem - I decided to give it a try based on your exchange above.

**Comment by CanoeFZH** [comment] 2015-06-10 11:27
@tng-konrad :+1:  let me know if you have any progress

**Comment by tng-konrad** [comment] 2015-06-10 11:29
Ok, so I changed the corpus. Output of running 

Konrads-MacBook-Pro:build konrad$ ./index config.toml 
1433935591: [info]     Creating index: ceeaus-inv (/Users/konrad/Documents/projects/meta/src/index/inverted_index.cpp:118)
 > Counting lines in file: [================================] 100% ETA 00:00:00 
 > Tokenizing Docs: [=======================================] 100% ETA 00:00:00 
 > Merging ceeaus-inv/chunk-0 (102.920000 KB) and ceeaus-inv/chunk-3 (108.370000 KB), 0 remaining        
1433935591: [info]     Created uncompressed postings file ceeaus-inv/postings.index (191.190000 KB) (/Users/konrad/Documents/projects/meta/src/index/inverted_index.cpp:133)
 > Compressing postings: [==================================] 100% ETA 00:00:00 
1433935591: [info]     Created compressed postings file (78.470000 KB) (/Users/konrad/Documents/projects/meta/src/index/inverted_index.cpp:261)
1433935591: [info]     Done creating index: ceeaus-inv (/Users/konrad/Documents/projects/meta/src/index/inverted_index.cpp:146)
Number of documents: 1008
Avg Doc Length: 128.236
Unique Terms: 3938
Index generation took: 0.438 seconds

The list of missing words (= output of ./print-vocab ceeaus-inv/termids.mapping )
 is rather long, seems to have 3938 entries => I won't include it here :-)

**Comment by CanoeFZH** [comment] 2015-06-10 11:34
@tng-konrad  But it seems that you does not post any error info above. Does it just have no error info?

**Comment by tng-konrad** [comment] 2015-06-10 11:38
Well, the ctest gives exact same error as your first post above - and ./index config.toml proceeds with no problem. Unless I misunderstood and you're asking sth else?

**Comment by CanoeFZH** [comment] 2015-06-10 11:44
@tng-konrad  I find where to change the config of corpus.  And I run the command ```./index xxx.toml ``` successfully and the ```./print-vocab``` command gives the same result as you said:
```
➜  build git:(master) ./print-vocab ceeaus-inv/termids.mapping  | sort | uniq | wc -l 
    3938
```
@smassung @skystrife  But does this have any relation with ctest error ? Or it is just a bug of ctest ?

**Comment by CanoeFZH** [comment] 2015-06-10 11:45
@tng-konrad I am also confused.

**Comment by smassung** [comment] 2015-06-10 13:52
Thanks for running the experiments. We will still need to the see the output from the vocabulary map. The 3938 you receive is the same 3938 from the ctest (where it should be 3944):

```
inverted-index-build-file-corpus:       [ FAIL ] [idx.unique_terms() == 3944ul] => [3938 == 3944] (inverted_index_test.cpp:69)
```

So, please paste the output of `print-vocab` on pastebin or similar and we will take a look at it to see why you have different terms.

**Comment by tng-konrad** [comment] 2015-06-10 13:56
Let me know if this one works http://pastebin.com/wFT3Mjvz

**Comment by skystrife** [comment] 2015-06-10 18:57
Thanks, that helps.

Unfortunately, I still can't reproduce this locally, even if I match your versions exactly.

What happens if you run

```
./tokenize-test config.toml
```

and give it the following (*exactly*) as input:

```
him.however,in
```

I get

```
<s> himhowev </s>
```

on all of the platforms I can test this on (OS X Yosemite w/ Apple LLVM 6.1.0 , Linux with GCC 5.1, Linux with Clang 3.6). Based on the vocab dump you gave me, it looks like you should get something different here (I'm curious as to what).

Thanks for the patience, btw. Really wish I could reproduce this locally, that would save us a ton of time...

**Comment by skystrife** [comment] 2015-06-10 19:07
Can you also try

```
him.however,interesting
```

as well?

I get:

```
<s> himhowev interest </s>
```

**Comment by tng-konrad** [comment] 2015-06-10 19:11
```
Konrads-MacBook-Pro:build konrad$ ./tokenize-test config.toml 
Type sentences to be tokenized. Hit enter with no text to exit.

> him.however,in

> 

```

more luck with the second one:
```
Konrads-MacBook-Pro:build konrad$ ./tokenize-test config.toml 
Type sentences to be tokenized. Hit enter with no text to exit.

> him.however,interesting
<s> interest </s>
> 

```

**Comment by skystrife** [comment] 2015-06-10 19:15
That is *really* weird. I was expecting it to at least produce a single token for the first one...

What about just:

```
himhowever
```
?

**Comment by tng-konrad** [comment] 2015-06-10 19:35
```
Konrads-MacBook-Pro:build konrad$ ./tokenize-test config.toml 
Type sentences to be tokenized. Hit enter with no text to exit.

> himhowever
<s> himhowev </s>
> 
```

Rg EDIT: meaning - a byte comparison? line 49 is the same.

**Comment by skystrife** [comment] 2015-06-10 20:22
I mean that whole function, not just that line.

**Comment by skystrife** [comment] 2015-06-10 20:26
Hmm... is the sentence splitting somehow different? What if you try

```
interesting.interesting,interesting
```

?

(These are all shots in the dark... thanks again for the patience.)

**Comment by tng-konrad** [comment] 2015-06-10 20:35
```
Konrads-MacBook-Pro:build konrad$ ./tokenize-test config.toml 
Type sentences to be tokenized. Hit enter with no text to exit.

> interesting.interesting,interesting
<s> interest interest interest </s>
> 
```
Based on https://www.diffchecker.com, it seems like my local version and the github one are identical up to whitespaces...

**Comment by skystrife** [comment] 2015-06-10 20:37
Can you upload your configuration file to a pastebin?

**Comment by tng-konrad** [comment] 2015-06-10 20:42
http://pastebin.com/mzWmwiKf

**Comment by skystrife** [comment] 2015-06-10 20:54
What happens if you try replacing line 29 of `src/utf/segmenter.cpp` with:

```cpp
const auto& locale = icu::Locale::getUS();
```

instead of

```cpp
const auto& locale = icu::Locale::getDefault();
```
(You'll need to recompile after making the change; just run `make` again)

Try the `interesting.interesting,interesting` input again.

**Comment by skystrife** [comment] 2015-06-10 21:18
Also, out of paranoia, let's make sure the ICU versions we've got are *exactly* the same between our OS X installs.

```
Chases-MBP:build chase$ shasum /usr/local/opt/icu4c/lib/libicudata.dylib
045e89fd3d2f9a0deaaeb45063bad912bd3bdbc0  /usr/local/opt/icu4c/lib/libicudata.dylib

Chases-MBP:build chase$ shasum /usr/local/opt/icu4c/lib/libicui18n.dylib
5b7333383355b2660f26ca883178a97649daf87f  /usr/local/opt/icu4c/lib/libicui18n.dylib

Chases-MBP:build chase$ shasum /usr/local/opt/icu4c/lib/libicuuc.dylib 
a753054373499a246dafe5281d45631d7249a9c2  /usr/local/opt/icu4c/lib/libicuuc.dylib
```

From what I can tell, it looks like the sentence segmentation we're getting is different, so I'm pretty sure this must be coming from ICU.

(I actually prefer what it seems to be doing for you, but that's beside the point...)

**Comment by CanoeFZH** [comment] 2015-06-11 00:15
@skystrife  same to yours
```
canoe:build/ (master) $ shasum /usr/local/opt/icu4c/lib/libicudata.dylib                                                                                                                                                            [8:13:57]
045e89fd3d2f9a0deaaeb45063bad912bd3bdbc0  /usr/local/opt/icu4c/lib/libicudata.dylib
canoe:build/ (master) $ shasum /usr/local/opt/icu4c/lib/libicui18n.dylib                                                                                                                                                            [8:14:06]
5b7333383355b2660f26ca883178a97649daf87f  /usr/local/opt/icu4c/lib/libicui18n.dylib
canoe:build/ (master) $ shasum /usr/local/opt/icu4c/lib/libicuuc.dylib                                                                                                                                                              [8:14:24]
a753054373499a246dafe5281d45631d7249a9c2  /usr/local/opt/icu4c/lib/libicuuc.dylib
```

**Comment by CanoeFZH** [comment] 2015-06-11 00:20
@skystrife I try all the test case you gave above and I have same result with @tng-konrad

**Comment by CanoeFZH** [comment] 2015-06-11 00:25
@skystrife After I change the 29th line of src/utf/segmenter.cpp: 
```
canoe:build/ (master✗) $ make                                                                                                                                                                             [8:23:58]
[  0%] Built target meta-util
[  3%] Built target meta-io
Scanning dependencies of target meta-utf
[  4%] Building CXX object src/utf/CMakeFiles/meta-utf.dir/segmenter.cpp.o
/Users/canoe/Project/meta/src/utf/segmenter.cpp:29:36: error: no member named 'getUs' in 'icu_55::Locale'
        const auto& locale = icu::Locale::getUs();
                             ~~~~~~~~~~~~~^
1 error generated.
make[2]: *** [src/utf/CMakeFiles/meta-utf.dir/segmenter.cpp.o] Error 1
make[1]: *** [src/utf/CMakeFiles/meta-utf.dir/all] Error 2
make: *** [all] Error 2
```
But it does not have a member named 'getUs' in 'icu_55::Locale'

**Comment by skystrife** [comment] 2015-06-11 03:50
`getUS()`, not `getUs()`.

**Comment by CanoeFZH** [comment] 2015-06-11 04:19
hmm ....

**Comment by tng-konrad** [comment] 2015-06-11 04:45
Ok, here are the checksums:

```
Konrads-MacBook-Pro:~ konrad$ cd Documents/projects/meta/build/
Konrads-MacBook-Pro:build konrad$ shasum /usr/local/opt/icu4c/lib/libicudata.dylib
045e89fd3d2f9a0deaaeb45063bad912bd3bdbc0  /usr/local/opt/icu4c/lib/libicudata.dylib
Konrads-MacBook-Pro:build konrad$ shasum /usr/local/opt/icu4c/lib/libicui18n.dylib
5b7333383355b2660f26ca883178a97649daf87f  /usr/local/opt/icu4c/lib/libicui18n.dylib
Konrads-MacBook-Pro:build konrad$ shasum /usr/local/opt/icu4c/lib/libicuuc.dylib 
a753054373499a246dafe5281d45631d7249a9c2  /usr/local/opt/icu4c/lib/libicuuc.dylib
Konrads-MacBook-Pro:build konrad$ 

```

**Comment by tng-konrad** [comment] 2015-06-11 08:10
And I also modified line 29 in segmenter.cpp, here's the subsequent output: 

```
Konrads-MacBook-Pro:build konrad$ ./tokenize-test config.toml 
Type sentences to be tokenized. Hit enter with no text to exit.

> interesting.interesting,interesting
<s> interestinginterest interest </s>
> 

```

**Comment by CanoeFZH** [comment] 2015-06-11 15:14
@skystrife  ```getUS()``` ... and ctest passed
```
canoe:build/ (master✗) $ ctest                                                                                                                                                                           [23:10:52]
Test project /Users/canoe/Project/meta/build
      Start  1: analyzers
 1/15 Test  #1: analyzers ........................   Passed    0.02 sec
      Start  2: stemmers
 2/15 Test  #2: stemmers .........................   Passed    0.09 sec
      Start  3: parallel
 3/15 Test  #3: parallel .........................   Passed    0.68 sec
      Start  4: inverted-index
 4/15 Test  #4: inverted-index ...................   Passed    1.24 sec
      Start  5: forward-index
 5/15 Test  #5: forward-index ....................   Passed    1.12 sec
      Start  6: string-list
 6/15 Test  #6: string-list ......................   Passed    0.00 sec
      Start  7: vocabulary-map
 7/15 Test  #7: vocabulary-map ...................   Passed    0.01 sec
      Start  8: libsvm-parser
 8/15 Test  #8: libsvm-parser ....................   Passed    0.00 sec
      Start  9: classifiers
 9/15 Test  #9: classifiers ......................   Passed    3.96 sec
      Start 10: rankers
10/15 Test #10: rankers ..........................   Passed    5.98 sec
      Start 11: ir-eval
11/15 Test #11: ir-eval ..........................   Passed    0.46 sec
      Start 12: compression
12/15 Test #12: compression ......................   Passed    0.05 sec
      Start 13: graph
13/15 Test #13: graph ............................   Passed    0.01 sec
      Start 14: parser
14/15 Test #14: parser ...........................   Passed    0.00 sec
      Start 15: filesystem
15/15 Test #15: filesystem .......................   Passed    0.00 sec

100% tests passed, 0 tests failed out of 15
```

**Comment by CanoeFZH** [comment] 2015-06-11 15:16
@smassung so what is the difference between  the two methods ```getUs()``` and ```getDefault()```?

**Comment by Send2steph** [comment] 2015-06-11 16:32
Hi, I am pretty new to Meta. Is see you fixed the problem? It has to do with replacing  line 29 of src/utf/segmenter.cpp  with const auto& locale = icu::Locale::getUS();  ?? 
Could you tell me how to do this step by step? thanks

**Comment by tng-konrad** [comment] 2015-06-11 18:05
Confirmed: after updating line 29 and rebuilding, everything works. Thanks!

**Comment by smassung** [comment] 2015-06-12 12:44
I'm assuming `getUS` is not returned by `getDefault` with your configuration for whatever reason. I'm also guessing we will patch the UTF segmenter to have `getUS` so as to avoid any different defaults in the future.

**Comment by fderyckere** [comment] 2015-06-13 09:48
FYI: Version 1.3.2 (used for the Coursera class on Text Retrieval and Search Engines) still works fine on my computer (with the getDefault() in segmenter.cpp), whereas I had the same issues as described above for version 1.3.6. Both seem to use the same version of ICU.

**Comment by skystrife** [comment] 2015-06-13 22:41
Fixed in 547d045, which is part of the v1.3.7 release.

**Closed by skystrife** 2015-06-13 22:41 UTC

**Comment by 4979** [comment] 2015-06-22 13:40
Hi,
After running "cp ../config.toml", how i can go for:-
# configure and build the project
CXX=clang++ cmake ../ -DCMAKE_BUILD_TYPE=Release -DICU_ROOT=/usr/local/opt/icu4c
and, 
make

Please guide me.
Thanks.

**Comment by nurur** [comment] 2015-11-14 03:09
I am trying to build MeTA on Mac 10.8. I can go all the way unto 'make' where I hit the wall as follows:

$ sudo make
Scanning dependencies of target porter2-stemmer
[  0%] Building CXX object deps/porter2_stemmer/CMakeFiles/porter2-stemmer.dir/porter2_stemmer.cpp.o
[  1%] Linking CXX static library libporter2-stemmer.a
[  1%] Built target porter2-stemmer
Scanning dependencies of target meta-utf
[  1%] Building CXX object src/utf/CMakeFiles/meta-utf.dir/segmenter.cpp.o
In file included from /Users/nururrahman/meta/src/utf/segmenter.cpp:8:
/Users/nururrahman/meta/src/utf/detail.h:12:10: fatal error: 'array' file not found
#include <array>
         ^
1 error generated.
make[2]: *** [src/utf/CMakeFiles/meta-utf.dir/segmenter.cpp.o] Error 1
make[1]: *** [src/utf/CMakeFiles/meta-utf.dir/all] Error 2


Any idea from anyone how to resolve this issue?
Thanks in advance.

**Comment by skystrife** [comment] 2015-11-15 08:19
What was the output of the `cmake` step?

**Comment by nurur** [comment] 2015-11-15 14:32
Here is the output of "cmake":

brahma> sudo CXX=clang++ cmake ../ -DCMAKE_BUILD_TYPE=Release -DICU_ROOT=/usr/local/opt/icu4c
-- The C compiler identification is AppleClang 5.1.0.5030040
-- The CXX compiler identification is AppleClang 5.1.0.5030040
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found ZLIB: /usr/lib/libz.dylib (found version "1.2.5") 
-- Looking for include file pthread.h
-- Looking for include file pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - found
-- Found Threads: TRUE  
-- Found ICU: /usr/local/opt/icu4c/lib/libicudata.dylib;/usr/local/opt/icu4c/lib/libicui18n.dylib;/usr/local/opt/icu4c/lib/libicuuc.dylib (found version "55.1.0") 
-- Performing Test HAS_CXX14
-- Performing Test HAS_CXX14 - Failed
-- Performing Test HAS_CXX1Y
-- Performing Test HAS_CXX1Y - Success
-- Compiler supports C++1y (using it)
-- Performing Test META_HAS_STD_SHARED_PTR_ATOMICS
-- Performing Test META_HAS_STD_SHARED_PTR_ATOMICS - Failed
-- Performing Test META_HAS_STREAM_MOVE
-- Performing Test META_HAS_STREAM_MOVE - Failed
-- Performing Test META_HAS_STD_MAKE_UNIQUE
-- Performing Test META_HAS_STD_MAKE_UNIQUE - Failed
-- Could NOT find Doxygen (missing:  DOXYGEN_EXECUTABLE) 
-- Locating libc++...
-- Located libc++, using it.
--     Locating libc++'s abi...
--     Found libc++abi, using it.
-- Performing Test CPPTOML_HAS_STD_PUT_TIME
-- Performing Test CPPTOML_HAS_STD_PUT_TIME - Failed
-- Performing Test CPPTOML_HAS_STD_REGEX
-- Performing Test CPPTOML_HAS_STD_REGEX - Failed
-- Could NOT find Doxygen (missing:  DOXYGEN_EXECUTABLE) 
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/nururrahman/meta/build

**Comment by skystrife** [comment] 2015-11-15 17:02
Hmm... Could you paste the output of a `make VERBOSE=1`?

It may be worth trying to re-install the Xcode command line tools.

**Comment by nurur** [comment] 2015-11-15 17:35
Do you think it might related to Xcode? I can reinstall and try it!
But here is the out put of make with verbose option:

brahma> sudo make VERBOSE=1

/usr/local/Cellar/cmake/3.3.2/bin/cmake -H/Users/nururrahman/meta -B/Users/nururrahman/meta/build --check-build-system CMakeFiles/Makefile.cmake 0
/usr/local/Cellar/cmake/3.3.2/bin/cmake -E cmake_progress_start /Users/nururrahman/meta/build/CMakeFiles /Users/nururrahman/meta/build/CMakeFiles/progress.marks
make -f CMakeFiles/Makefile2 all
make -f deps/porter2_stemmer/CMakeFiles/porter2-stemmer.dir/build.make deps/porter2_stemmer/CMakeFiles/porter2-stemmer.dir/depend
cd /Users/nururrahman/meta/build && /usr/local/Cellar/cmake/3.3.2/bin/cmake -E cmake_depends "Unix Makefiles" /Users/nururrahman/meta /Users/nururrahman/meta/deps/porter2_stemmer /Users/nururrahman/meta/build /Users/nururrahman/meta/build/deps/porter2_stemmer /Users/nururrahman/meta/build/deps/porter2_stemmer/CMakeFiles/porter2-stemmer.dir/DependInfo.cmake --color=
Dependee "/Users/nururrahman/meta/build/deps/porter2_stemmer/CMakeFiles/porter2-stemmer.dir/DependInfo.cmake" is newer than depender "/Users/nururrahman/meta/build/deps/porter2_stemmer/CMakeFiles/porter2-stemmer.dir/depend.internal".
Dependee "/Users/nururrahman/meta/build/deps/porter2_stemmer/CMakeFiles/CMakeDirectoryInformation.cmake" is newer than depender "/Users/nururrahman/meta/build/deps/porter2_stemmer/CMakeFiles/porter2-stemmer.dir/depend.internal".
Scanning dependencies of target porter2-stemmer
make -f deps/porter2_stemmer/CMakeFiles/porter2-stemmer.dir/build.make deps/porter2_stemmer/CMakeFiles/porter2-stemmer.dir/build
[  0%] Building CXX object deps/porter2_stemmer/CMakeFiles/porter2-stemmer.dir/porter2_stemmer.cpp.o
cd /Users/nururrahman/meta/build/deps/porter2_stemmer && /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++   -DMETA_HAS_CXX14=1 -DMETA_HAS_ZLIB -DMETA_IS_DARWIN=1 -D_DARWIN_USE_64_BIT_INODE=1 -Wall -Wextra -pedantic -std=c++1y  -Wall -pedantic -O3 -DNDEBUG -I/Users/nururrahman/meta/include -isystem /usr/local/opt/icu4c/include -I/Users/nururrahman/meta/deps/porter2_stemmer -I/Users/nururrahman/meta/deps/cpptoml/include    -std=c++11 -stdlib=libc++ -std=c++1y -o CMakeFiles/porter2-stemmer.dir/porter2_stemmer.cpp.o -c /Users/nururrahman/meta/deps/porter2_stemmer/porter2_stemmer.cpp
[  1%] Linking CXX static library libporter2-stemmer.a
cd /Users/nururrahman/meta/build/deps/porter2_stemmer && /usr/local/Cellar/cmake/3.3.2/bin/cmake -P CMakeFiles/porter2-stemmer.dir/cmake_clean_target.cmake
cd /Users/nururrahman/meta/build/deps/porter2_stemmer && /usr/local/Cellar/cmake/3.3.2/bin/cmake -E cmake_link_script CMakeFiles/porter2-stemmer.dir/link.txt --verbose=1
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ar cq libporter2-stemmer.a  CMakeFiles/porter2-stemmer.dir/porter2_stemmer.cpp.o
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib libporter2-stemmer.a
[  1%] Built target porter2-stemmer
make -f src/utf/CMakeFiles/meta-utf.dir/build.make src/utf/CMakeFiles/meta-utf.dir/depend
cd /Users/nururrahman/meta/build && /usr/local/Cellar/cmake/3.3.2/bin/cmake -E cmake_depends "Unix Makefiles" /Users/nururrahman/meta /Users/nururrahman/meta/src/utf /Users/nururrahman/meta/build /Users/nururrahman/meta/build/src/utf /Users/nururrahman/meta/build/src/utf/CMakeFiles/meta-utf.dir/DependInfo.cmake --color=
Dependee "/Users/nururrahman/meta/build/src/utf/CMakeFiles/meta-utf.dir/DependInfo.cmake" is newer than depender "/Users/nururrahman/meta/build/src/utf/CMakeFiles/meta-utf.dir/depend.internal".
Dependee "/Users/nururrahman/meta/build/src/utf/CMakeFiles/CMakeDirectoryInformation.cmake" is newer than depender "/Users/nururrahman/meta/build/src/utf/CMakeFiles/meta-utf.dir/depend.internal".
Scanning dependencies of target meta-utf
make -f src/utf/CMakeFiles/meta-utf.dir/build.make src/utf/CMakeFiles/meta-utf.dir/build
[  1%] Building CXX object src/utf/CMakeFiles/meta-utf.dir/segmenter.cpp.o
cd /Users/nururrahman/meta/build/src/utf && /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++   -DMETA_HAS_CXX14=1 -DMETA_HAS_ZLIB -DMETA_IS_DARWIN=1 -D_DARWIN_USE_64_BIT_INODE=1 -Wall -Wextra -pedantic -std=c++1y  -O3 -DNDEBUG -I/Users/nururrahman/meta/include -isystem /usr/local/opt/icu4c/include -I/Users/nururrahman/meta/deps/cpptoml/include    -std=c++1y -o CMakeFiles/meta-utf.dir/segmenter.cpp.o -c /Users/nururrahman/meta/src/utf/segmenter.cpp
In file included from /Users/nururrahman/meta/src/utf/segmenter.cpp:8:
/Users/nururrahman/meta/src/utf/detail.h:12:10: fatal error: 'array' file not found
#include <array> 
         ^
1 error generated.
make[2]: *** [src/utf/CMakeFiles/meta-utf.dir/segmenter.cpp.o] Error 1
make[1]: *** [src/utf/CMakeFiles/meta-utf.dir/all] Error 2
make: *** [all] Error 2

**Comment by nurur** [comment] 2015-11-15 17:36
note that < array >  appears after #include.

**Comment by skystrife** [comment] 2015-11-15 18:56
OK, that last paste helped a lot. I think the problem might be on our end.

Can you try changing the last line in `src/utf/CMakeLists.txt` from

```cmake
target_link_libraries(meta-utf ${ICU_LIBRARIES})
```

to

```cmake
target_link_libraries(meta-utf meta-definitions ${ICU_LIBRARIES})
```

and see if that helps?

**Comment by nurur** [comment] 2015-11-15 19:38
I did. Unfortunately the problem with "array" persists!



brahma> sudo make VERBOSE=1
/usr/local/Cellar/cmake/3.3.2/bin/cmake -H/Users/nururrahman/meta -B/Users/nururrahman/meta/build --check-build-system CMakeFiles/Makefile.cmake 0
/usr/local/Cellar/cmake/3.3.2/bin/cmake -E cmake_progress_start /Users/nururrahman/meta/build/CMakeFiles /Users/nururrahman/meta/build/CMakeFiles/progress.marks
make -f CMakeFiles/Makefile2 all
make -f deps/porter2_stemmer/CMakeFiles/porter2-stemmer.dir/build.make deps/porter2_stemmer/CMakeFiles/porter2-stemmer.dir/depend
cd /Users/nururrahman/meta/build && /usr/local/Cellar/cmake/3.3.2/bin/cmake -E cmake_depends "Unix Makefiles" /Users/nururrahman/meta /Users/nururrahman/meta/deps/porter2_stemmer /Users/nururrahman/meta/build /Users/nururrahman/meta/build/deps/porter2_stemmer /Users/nururrahman/meta/build/deps/porter2_stemmer/CMakeFiles/porter2-stemmer.dir/DependInfo.cmake --color=
make -f deps/porter2_stemmer/CMakeFiles/porter2-stemmer.dir/build.make deps/porter2_stemmer/CMakeFiles/porter2-stemmer.dir/build
make[2]: Nothing to be done for `deps/porter2_stemmer/CMakeFiles/porter2-stemmer.dir/build'.
[  1%] Built target porter2-stemmer
make -f src/utf/CMakeFiles/meta-utf.dir/build.make src/utf/CMakeFiles/meta-utf.dir/depend
cd /Users/nururrahman/meta/build && /usr/local/Cellar/cmake/3.3.2/bin/cmake -E cmake_depends "Unix Makefiles" /Users/nururrahman/meta /Users/nururrahman/meta/src/utf /Users/nururrahman/meta/build /Users/nururrahman/meta/build/src/utf /Users/nururrahman/meta/build/src/utf/CMakeFiles/meta-utf.dir/DependInfo.cmake --color=
make -f src/utf/CMakeFiles/meta-utf.dir/build.make src/utf/CMakeFiles/meta-utf.dir/build
[  1%] Building CXX object src/utf/CMakeFiles/meta-utf.dir/segmenter.cpp.o
cd /Users/nururrahman/meta/build/src/utf && /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++   -DMETA_HAS_CXX14=1 -DMETA_HAS_ZLIB -DMETA_IS_DARWIN=1 -D_DARWIN_USE_64_BIT_INODE=1 -Wall -Wextra -pedantic -std=c++1y  -O3 -DNDEBUG -I/Users/nururrahman/meta/include -isystem /usr/local/opt/icu4c/include -I/Users/nururrahman/meta/deps/cpptoml/include    -std=c++1y -o CMakeFiles/meta-utf.dir/segmenter.cpp.o -c /Users/nururrahman/meta/src/utf/segmenter.cpp
In file included from /Users/nururrahman/meta/src/utf/segmenter.cpp:8:
/Users/nururrahman/meta/src/utf/detail.h:12:10: fatal error: 'array' file not found
#include < array >
         ^
1 error generated.
make[2]: *** [src/utf/CMakeFiles/meta-utf.dir/segmenter.cpp.o] Error 1
make[1]: *** [src/utf/CMakeFiles/meta-utf.dir/all] Error 2
make: *** [all] Error 2
