### ISSUE TITLE
PerceptronTagger hangs

### ISSUE THREAD

**Issue by magic-lantern** [meta-toolkit/meta#188] opened 2017-08-16 15:02 UTC
From today's demo at KDD 2017 - wether running 

`tagger = metapy.sequence.PerceptronTagger("perceptron-tagger/")
`

either inside Jupyter or via command-line python, the above line of code appears to hang - no error is output, but never completed. Others said that killing the kernel and restarting worked - but didn't work for me.

As an FYI, here's what Python I'm running on macOS Sierra 10.12.6:

python --version
Python 3.6.1 :: Anaconda custom (x86_64)

python --version
Python 2.7.13 :: Continuum Analytics, Inc.

**Comment by skystrife** [comment] 2017-08-16 17:57
Thanks for the report. I was just able to reproduce this; it looks like it is a deadlock contention for the python GIL to print loading progress output if `metapy.log_to_stderr()` was called first.

This has been fixed in meta-toolkit/metapy@23bd3c0 and should be available once the build jobs for v0.2.6 finish and I can upload the new library version to PyPI.

**Comment by magic-lantern** [comment] 2017-08-16 19:48
Thanks for the quick look and resolution.

**Comment by skystrife** [comment] 2017-08-16 21:45
The new version has just finished deployment, so you should be able to grab the latest version with the fix with:

```bash
pip install --upgrade metapy
```

**Closed by skystrife** 2017-08-16 21:45 UTC

**Comment by magic-lantern** [comment] 2017-08-17 18:39
Just wanted to let you know that I've confirmed this is resolved as well.
