### ISSUE TITLE
Precision and Recall Issue

### ISSUE THREAD

**Issue by husseinhazimeh** [meta-toolkit/meta#104] opened 2015-08-30 22:53 UTC
It seems that the precision and recall values reported by the confusion matrix, specifically the stats() method, are being flipped (I tried running it on several datasets and got flipped values)

**Comment by smassung** [comment] 2015-08-31 16:14
Hi Hussein, let me see if I can pinpoint where the problem is. I'm assuming you've looked at the code? [This line and the following](https://github.com/meta-toolkit/meta/blob/master/src/classify/confusion_matrix.cpp#L107) is a spot where they could potentially be switched.

In printing at least, it looks like precision and recall are being printed in the correct columns. [Column label printing](https://github.com/meta-toolkit/meta/blob/master/src/classify/confusion_matrix.cpp#L150) and [value printing](https://github.com/meta-toolkit/meta/blob/master/src/classify/confusion_matrix.cpp#L124).

If you think the issue is in the first line of code I linked, please let me know and I'll take a further look into it.

**Comment by husseinhazimeh** [comment] 2015-08-31 16:44
Hi Sean, 

Yeah most probably the problem lies in lines 107 and 108; by switching the precision and recall assignments, the correct values will be printed. However, I didn't follow all the code so I cannot pinpoint the issue.

Thanks!

**Comment by smassung** [comment] 2015-08-31 17:02
I think you're right, the two lines are doing the opposite of what they are supposed to be doing:

```cpp
for (auto& cls : classes_)
{
    prec += map::safe_at(predictions_, std::make_pair(cls, label));  // line 1
    rec += map::safe_at(predictions_, std::make_pair(label, cls));    // line 2
}

double correct = map::safe_at(predictions_, std::make_pair(label, label));  // line 3

if (rec != 0.0)
    rec = correct / rec;

if (prec != 0.0)
    prec = correct / prec;
```

Say we have three classes `{A,B,C}` and we want to find the precision and recall for `label=B`. We iterate over all three classes and query the `predictions_` map, which maps `predicted -> actual -> count` where `count` is the total number of times `predicted` is classified as `actual`. Line 1 computes the sum of all the `actual B` labels in the dataset (which is the denominator for recall!). Line 2 computes the sum of all the times `B` we predicted, which is the denominator for precision. Line 3 is the total number of correct `B` classifications. So, I believe it should be changed to:

```cpp
for (auto& cls : classes_)
{
    prec += map::safe_at(predictions_, std::make_pair(label, cls));  // line 1
    rec += map::safe_at(predictions_, std::make_pair(cls, label));    // line 2
}
```

@skystrife, can we get a final opinion/confirmation before I make the changes?

**Comment by smassung** [comment] 2015-08-31 19:42
I believe it's fixed now after writing a unit test for it; pushing my commits now. Let's make a patch release after you check it over one last time.

**Comment by skystrife** [comment] 2015-08-31 20:38
Unit test would have been the only thing I would have suggested. I have some feedback on that commit, see the [line notes I left](https://github.com/meta-toolkit/meta/commit/e034c6c01ac2b66a086b25e71c7e4988dbd93c08).

One other thing that comes to mind: can we prevent bugs like this in the future by using opaque identifiers? Maybe make a `predicted_label` and `actual_label` and have the map be from `std::pair<predicted_label, actual_label>` which should force us to make sure we're interacting with the map in the right order (at least in debug mode)?

**Comment by smassung** [comment] 2015-08-31 21:05
I'll make the stats functions be dynamically calculated. I couldn't decide whether to do it when I was making the fix, but I agree that it would make the unit tests much better.

As for the identifiers, I could add a `predicted_label` and just keep `class_label` as the actual label I think?

**Comment by smassung** [comment] 2015-08-31 22:50
Changes applied in master. Thanks @husseinhazimeh for catching this! Will make a new release soon.

**Closed by smassung** 2015-08-31 22:50 UTC

**Comment by husseinhazimeh** [comment] 2015-08-31 23:08
Thanks Sean for the quick fix! I tested the latest version and everything is working properly now.

**Comment by smassung** [comment] 2015-08-31 23:09
Excellent. I'm curious as to how you were testing it, did you just do some manual calculations and check them for a small dataset?

**Comment by husseinhazimeh** [comment] 2015-08-31 23:20
I actually implemented some of the measures (such as accuracy, precision, recall, etc) in Python for the leaderboard of the MOOC and cross-checked the values between my scripts and MeTA..
